---
title: "Challenge 1, Part 1"
subtitle: "Part 1"
output: html_notebook
---

```{r}
x <- runif(20, 0, 100)
y <- 5*x + rnorm(20, 0, 10)
df <- data.frame(x, y)
df
plot(df)

mod <- lm(y ~ x, data = df)

```
http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/

```{r}
library(ggplot2)

```


```{r}
set.seed(955)
# Make some noisily increasing data
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))
head(dat)

```

```{r}
ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1)      # Use hollow circles

ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm)   # Add linear regression line 
                             #  (by default includes 95% confidence region)

ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm,   # Add linear regression line
                se=FALSE)    # Don't add shaded confidence region


ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth()            # Add a loess smoothed fit curve with confidence region
#> `geom_smooth()` using method = 'loess'
```

```{r}
ggplot(dat, aes(x=xvar, y=yvar, color=cond)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm, color="black", fill="black")
```

```{r}
#> https://ggplot2.tidyverse.org/reference/geom_smooth.html#examples
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  geom_smooth(se = FALSE, method = lm)
#> `geom_smooth()` using method = 'loess'
```
```{r}
# https://ggplot2.tidyverse.org/index.html
library(ggplot2)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point()
```

```{r}
# https://ggplot2.tidyverse.org/index.html
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```
```{r}
# https://ggplot2.tidyverse.org/index.html
library(ggplot2)

ggplot(mpg, aes(cty, hwy, colour = class)) + 
  geom_point()
```

```{r}
# https://ggplot2.tidyverse.org/index.html
library(ggplot2)

ggplot(mpg, aes(cty, hwy, colour = class)) + 
  geom_point(alpha=0.2)
```

```{r}
# https://ggplot2.tidyverse.org/index.html
library(ggplot2)

ggplot(mpg, aes(cty, hwy)) + 
  geom_point(alpha=0.2)
```


```{r}
mpg
```


